/**
 * Ollama service - replaces AWS Bedrock with local LLM
 * Requires Ollama running locally on http://localhost:11434
 */

const OLLAMA_URL = 'http://localhost:11434/api/generate'
const MODEL = 'llama3.2:1b' // Using 1B model for faster generation

/**
 * Generates a single behavioral interview question for the given category.
 * @param {string} [category='behavioral'] - The question category (e.g. 'leadership', 'teamwork')
 * @returns {Promise<string>} The generated question text
 */
export async function generateQuestion(category = 'behavioral') {
  const prompt = `Generate one ${category} interview question for entry-level candidates. Question only:`

  const response = await fetch(OLLAMA_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: MODEL,
      prompt: prompt,
      stream: false,
      options: {
        temperature: 0.8,
        num_predict: 50,
        num_ctx: 512,
      },
    }),
  })

  if (!response.ok) {
    throw new Error(`Ollama request failed: ${response.statusText}`)
  }

  const data = await response.json()
  const question = data.response?.trim()

  if (!question) {
    throw new Error('No question generated by Ollama')
  }

  return question
}

/**
 * Analyzes a candidate's interview response and returns structured STAR feedback.
 * @param {string} question - The behavioral interview question that was asked
 * @param {string} transcription - The candidate's spoken response (transcribed)
 * @returns {Promise<Feedback>} Structured feedback object
 *
 * @typedef {Object} Feedback
 * @property {{ situation: boolean, task: boolean, action: boolean, result: boolean }} starAnalysis
 * @property {string[]} strengths
 * @property {string[]} areasForImprovement
 * @property {string[]} actionableTips
 */
export async function analyzeResponse(question, transcription) {
  const prompt = `You are an expert interview coach. Analyze this behavioral interview response using the STAR framework.

Question: ${question}

Candidate's Response: ${transcription}

Provide detailed, constructive feedback in JSON format:

{
  "starAnalysis": {
    "situation": true/false (Did they describe the context/background?),
    "task": true/false (Did they explain their responsibility/goal?),
    "action": true/false (Did they detail specific actions they took?),
    "result": true/false (Did they share measurable outcomes/impact?)
  },
  "strengths": [
    "List 2-3 specific things they did well",
    "Be encouraging and specific"
  ],
  "areasForImprovement": [
    "List 2-3 specific gaps or areas to strengthen",
    "Focus on what's missing from STAR"
  ],
  "actionableTips": [
    "Provide 2-3 concrete, specific suggestions",
    "Make them immediately actionable for next time"
  ]
}

Return ONLY valid JSON, no markdown or explanation.`

  const response = await fetch(OLLAMA_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'llama3.2:latest', // Use larger 3.2B model for better analysis
      prompt: prompt,
      stream: false,
      options: {
        temperature: 0.4,
        num_predict: 1000,
        num_ctx: 4096,
      },
    }),
  })

  if (!response.ok) {
    throw new Error(`Ollama request failed: ${response.statusText}`)
  }

  const data = await response.json()
  const rawText = data.response?.trim()

  if (!rawText) {
    throw new Error('No analysis generated by Ollama')
  }

  // Strip markdown code fences if present
  let jsonText = rawText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim()
  
  // Fix incomplete JSON by adding missing closing braces
  const openBraces = (jsonText.match(/{/g) || []).length
  const closeBraces = (jsonText.match(/}/g) || []).length
  if (openBraces > closeBraces) {
    jsonText += '}'.repeat(openBraces - closeBraces)
  }

  let feedback
  try {
    feedback = JSON.parse(jsonText)
  } catch (err) {
    throw new Error(`Ollama returned malformed JSON: ${err.message}. Raw response: ${rawText}`)
  }

  // Ensure all required fields exist with defaults
  feedback.starAnalysis = feedback.starAnalysis || { situation: false, task: false, action: false, result: false }
  feedback.strengths = feedback.strengths || []
  feedback.areasForImprovement = feedback.areasForImprovement || []
  feedback.actionableTips = feedback.actionableTips || []

  return feedback
}
