/**
 * Ollama service - replaces AWS Bedrock with local LLM
 * Requires Ollama running locally on http://localhost:11434
 */

const OLLAMA_URL = 'http://localhost:11434/api/generate'
const MODEL = 'llama3.2' // or 'mistral', 'llama3', etc.

/**
 * Generates a single behavioral interview question for the given category.
 * @param {string} [category='behavioral'] - The question category (e.g. 'leadership', 'teamwork')
 * @returns {Promise<string>} The generated question text
 */
export async function generateQuestion(category = 'behavioral') {
  const prompt = `You are an interview coach helping college students and entry-level candidates practice behavioral interviews. Generate exactly one behavioral interview question from the following category: ${category}. Return only the question text, no preamble or explanation.`

  const response = await fetch(OLLAMA_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: MODEL,
      prompt: prompt,
      stream: false,
      options: {
        temperature: 0.8,
        num_predict: 100,
      },
    }),
  })

  if (!response.ok) {
    throw new Error(`Ollama request failed: ${response.statusText}`)
  }

  const data = await response.json()
  const question = data.response?.trim()

  if (!question) {
    throw new Error('No question generated by Ollama')
  }

  return question
}

/**
 * Analyzes a candidate's interview response and returns structured STAR feedback.
 * @param {string} question - The behavioral interview question that was asked
 * @param {string} transcription - The candidate's spoken response (transcribed)
 * @returns {Promise<Feedback>} Structured feedback object
 *
 * @typedef {Object} Feedback
 * @property {{ situation: boolean, task: boolean, action: boolean, result: boolean }} starAnalysis
 * @property {string[]} strengths
 * @property {string[]} areasForImprovement
 * @property {string[]} actionableTips
 */
export async function analyzeResponse(question, transcription) {
  const prompt = `You are an encouraging interview coach. Analyze the following interview response using the STAR framework (Situation, Task, Action, Result).

Question: ${question}

Response: ${transcription}

Return ONLY a JSON object with these exact fields:
- starAnalysis: object with boolean fields situation, task, action, result
- strengths: array of strings (1-3 specific things done well)
- areasForImprovement: array of strings (1-3 specific gaps or weaknesses)
- actionableTips: array of exactly 2-3 concrete, actionable suggestions

Use an encouraging, supportive tone. Return ONLY the JSON, no markdown formatting or explanation.`

  const response = await fetch(OLLAMA_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: MODEL,
      prompt: prompt,
      stream: false,
      options: {
        temperature: 0.5,
        num_predict: 500,
      },
    }),
  })

  if (!response.ok) {
    throw new Error(`Ollama request failed: ${response.statusText}`)
  }

  const data = await response.json()
  const rawText = data.response?.trim()

  if (!rawText) {
    throw new Error('No analysis generated by Ollama')
  }

  // Strip markdown code fences if present
  const jsonText = rawText.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim()

  let feedback
  try {
    feedback = JSON.parse(jsonText)
  } catch (err) {
    throw new Error(`Ollama returned malformed JSON: ${err.message}. Raw response: ${rawText}`)
  }

  return feedback
}
